services:
  db:
    image: timescale/timescaledb-ha:pg18
    user: 1000:1000
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /pgdata
    volumes:
      - ./pgsqldata:/pgdata

  adminer:
    image: adminer
    ports:
      - "8080:8080"


