[tools]

rust = { version = "latest", profile = "default", components = "rust-src" }
"github:rust-lang/mdbook" = "0.5.2"
"cargo:mdbook-gitinfo" = "2.0.0"
# Fork of mdbook-cmdrun with mdbook 0.5 support
"cargo:https://github.com/roberth/mdbook-cmdrun" = "rev:3947c797d063352e0f983311c078430215cc1cca"
jq = "1.8.1"
"cargo:tokio-console" = "latest"

[env]
CSC_PROTO = "https"
CSC_HOST = "mycscgo.com"
CSC_PORT = ""
CSC_UA = ""

# Databas
DB_TYPE = "postgres"
DB_HOST = "localhost"
DB_PORT = "5432"
# Dev creds only
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASS = "password"


[tasks.docs]
description = "Runs docs:build"
depends = "docs:build"

[tasks."docs:render"]
description = "Renders Schemas to an SVG"
run = [
    "dbml-renderer -i docs/schema.dbml -o docs/assets/schema.svg"
]
sources = ["docs/schema.dbml"]
outputs = ["docs/assets/schema.svg"]
tools."npm:@dbml/cli" = "latest"
tools."npm:@softwaretechnik/dbml-renderer" = "latest"

[tasks."docs:build"]
depends = "docs:render"
description = "Use MdBook to generate documentation"
run = "mdbook build"

[tasks."docs:serve"]
depends = "docs:render"
description = "Uses MdBook to serve live documentation"
run = "mdbook serve --open"

[tasks."docs:clean"]
description = "Cleans mdbook directories and generated assets"
run = [
    "mdbook clean",
    "rm docs/assets/schema.svg docs/assets/extended_schema.svg",
]

[tasks.db]
description = "Run db:up"
run = "db:up"

[tasks.app]
description = "Run app:build"
depends = "app:build"

[tasks."app:clean"]
description = "Clean cargo build files"
run = "cargo clean"


# Task templates
[settings]
experimental = true

[tasks."app:run"]
run = 'cargo run '
env = { RUST_LOG = "debug,laundry_data=debug,h2=error" }

[tasks."app:build"]
run = 'cargo build --release'

[tasks."app:check"]
run = 'cargo clippy '

[tasks."app:deps"]
description = "Build a dependency tree using cargo"
run = 'cargo tree '


[tasks."db:clean"]
description = "Clean left over database files"
run = "rm -rf pgsqldata"

[tasks."db:pre"]
description = "Ran before db:up"
run = "mkdir -p pgsqldata"
run_windows = "mkdir pgsqldata"
outputs = "pgsqldata"

[tasks."db:up"]
depends = "db:pre"
description = "Start docker compose"
run = "docker compose -f compose.yaml up -d"

[tasks."db:ps"]
description = "Check running docker compose containers"
run = "docker compose -f compose.yaml ps"

[tasks."db:logs"]
description = "Check docker compose logs"
run = "docker compose -f compose.yaml logs --follow"

[tasks."db:down"]
description = "Stop docker compose"
run = "docker compose -f compose.yaml down"

