### Get location
GET {{host}}/api/v1/location/{{location_id}}
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

>>! res/location/{{location_id}}.json


### Get room summary
GET {{host}}/api/v1/location/{{location_id}}/room/{{room_id}}/summary
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

>>! res/summary/{{location_id}}/{{room_id}}.json


### Get all room machine
GET {{host}}/api/v1/location/{{location_id}}/room/{{room_id}}/machines
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

>>! res/machines/{{location_id}}/{{room_id}}.json


### Location search by lon, lat
GET {{host}}/api/v1/location/search?
    latitude={{latitude}}&
    longitude={{longitude}}&
    radius=5&
    limit=10
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

>>! res/search/{{$random.uuid}}.json

### Get machine by sticker, location, room id
GET {{host}}/api/v1/machine/number/1?
    locationId={{location_id}}&
    roomId={{room_id}}
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

### Api Stream
GET {{host}}/api/v1/events/stream?
    licensePlates={{license_plate}}&
    locationId={{location_id}}
Accept-Language: en-US
User-Agent: {{user_agent}}
accept: application/json

>>! res/stream/{{location_id}}/{{$random.uuid}}.json

