
// Temps based on archived api docs
// WasherTemp, DryerTemp, MachineSettings (stored as json)

enum WasherTemp {
  cold
  warm
  host
}

enum DryerTemp {
  high_temp // high-temp
  med_temp // med-temp
  low_temp // low-temp
  no_temp // no-temp
  delicates
}

enum MachineSoil {
  normal
  light
  medium
  heavy
}

enum MachineCycle {
  normal
  perm_press // perm-press
  delicates
}

enum CSCTechnology {
  CSCGo
  DI
}
