Project LaundryData {
  database_type: 'PostgreSQL'
  Note: '''
    requires Postgres >=18, and timescale latest version

    docker setup:
      https://www.tigerdata.com/docs/self-hosted/latest/install/installation-docker

    Fast joins using CTE:
      https://www.tigerdata.com/docs/tutorials/latest/cookbook#get-faster-join-queries-with-common-table-expressions

    csc api docs:
      https://web.archive.org/web/20240120071238/https://mycscgo.com/api/v1/docs/static/index.html#/Events/EventsController_events


      opaqueId is global machine id
  
    TODO:
      - Materialized view? based on locations. A temp table for every location.
      - A machine history. Another table with machine id and room id in case a machine moves accorss rooms or locations
      - Primary key describes a little bit of the row. timestamp + hash(important value)

    Wishes:
      - backfilling
  '''
}

Table Laundry {
  id uuid [pk, note:'UUID v7 has the timestamp for timescale', default: `uuidv7()`]
  timestamp timestamptz [not null]
  machine_id int [not null,ref: < Machines.id]
  current_state MachineState [not null]
  time_remaining smallint [note: 'How long the machine will run for', not null]

  // csc fields
  door_closed bool [not null]
  available bool [not null]
  not_available_reason text [note: 'TODO: find all reasons it may not be available', not null]

  machine_settings json [note: 'Json because it is simple to handle and pg supports queries inside.', not null, default: `{}`]

  note: '''
    Every row repersents the state of a machine at a point in time.
    Will grow quickly if collecting more than oregontech machines.

    Does not include a timestamp column, extract timestamp from uuid if needed.
      https://www.tigerdata.com/docs/api/latest/uuid-functions

    Discussion 1/29:
      Primary keys should have data related to the row. UUID is a random value with no relation to data.
      This is the "log" table, it has every part of the response for the api.

    Extra:
    create as a hypertable
      https://www.tigerdata.com/docs/use-timescale/latest/hypertables/hypertable-crud

      WITH (
        tsdb.hypertable,
        tsdb.orderby='time',
        tsdb.partition_column = 'id'
      )
  '''
}

Table Machines {
  id int [pk, note:'Global machine id', not null]
  room_id int [not null, ref: > Rooms.id]
  type MachineType [not null]
  last_seen timestamptz [not null]

  // csc fields
  csc_id uuid [not null, unique, note: 'AKA Opaque Id']
  license_plate varchar(7) [not null, note: 'follows a standard "000-AAA"']
  sticker_number smallint [not null]
  nfc_id uuid [not null]
  qr_code_id text [not null, note: 'Not sure if value will stay 5 Char in length']
  capability json [null, default: {} ]
  stack text [null, note: 'either upper ']

  note:'''
    A machine may be replaced. 
    TODO: need mechanism to keep track of a spot at a location. Stickernumber vs Machine id
  '''
}

Table Rooms {
  id int [pk, not null]
  csc_id int [not null]
  description text [null]
  washer_count smallint [not null]
  dryer_count smallint [not null]
  location_id int [not null, ref: > Locations.id]
}

Table Locations {
  id int [pk, not null, note: "Global location id"]
  csc_id int [not null]
  address text [not null]
  washer_sum smallint [note: 'Update using trigger and join all rooms']
  dryer_sum smallint [note: 'Update using trigger and join all rooms']
  timezone text [not null,note:'The timezone a location is in. See "pg_timezone_names"']
}

enum MachineState {
  pressStart
  running
  idle
  unknown
}

enum MachineType {
  washer
  dryer
}

Table ApiLog {
  id int [pk, not null]
  timestamp timestamptz [not null]
  code smallint [not null, note:'Http Response code']
  status ApiStatus [not null, default: ApiStauts.unknown, note: 'api status for timestamp. Need to fill in ApiStatus better']
  message text [not null, note: 'Will contain an error message']
  json_hash text [not null, note: 'Hash of json response']
}
// TODO: Fill in
enum ApiStatus {
  up
  down
  failure
  unknown
}
