project LaundryData {
  note: '''
    # Overview
    Apply these conditions regardless of the chosen database

    0. If any schema changes are made that do not follow the any conditions.
      Document the changes in a comment at the end of the script.
    1. Foreign keys are defined on the table creation, and not in row. They are only created at the end
      of the table using the FOREIGN KEY REFERENCES syntax.
    2. If any dialect exclusive features are included replicate them in the best way for the database
      and add a comment documenting the removal.
    3. If a column uses data type VARCHAR with a set length, add a constraint to ensure maintained length.


    # Postgres
    Postgres Conversion Standards. Apply these conditions when converting to postgres.

    1. Create 'LaundryLog' as a Timescale Hypertable using a with statement. The following arguments apply.
      a. 'tsdb.partition_column' is 'timestamp'
      b. 'tsdb.chunk_interval' is '1 day'


    # SQL Server
    Sql Server Conversion standards. Apply these conditions when converting to sql server.

    
    # Sqlite
    SQLITE Conversion standards. Apply these conditions when converting to sqlite.

    1. Primary keys, the columns named "id", are always going to have the integer data type with
      primary key and autoincrement conditions. This does not include columns with "id" in the name.
    2. Any column that is of type UUID should be converted to TEXT.
    3. Any column that is of type JSON should be converted to TEXT. Do not include any checks for valid JSON
    4. Any column that is of type TIMESTAMPTZ and other time columns should be converted to TEXT.
    5. If any integer data type is missing, use INTEGER.

  '''
}

table PhysicalEndpoint {
  // Pep is derived from room, location, and machine
  
  // added_on exists to allow latest lookup of a machine given
  // location, room, sticker number
  pep_id text [not null]
  added_on timestamptz [not null, default: "CURRENT_DATE"]

  room_id text [pk, ref: > Rooms.room_id]
  location_id uuid [pk, ref: > Locations.location_id]
  machine_id uuid [pk, ref: > Machines.machine_id]
  sticker_number int [pk]
}

table LaundryLog {
  pep_id text [pk, not null, ref: < PhysicalEndpoint.pep_id]
  timestamp timestamptz [pk, not null]

  // Current time remaining on the display.
  // Can go up between checks
  time_remaining smallint [not null]
  // Will be null if available
  not_available_reason text [null]
  door_closed bool [not null]
  // aka mode
  state MachineState [not null] 
  machine_settings json
}

table Locations {
  location_id uuid [pk]
  description text 
  label text [not null]

  // mssql: add check for in 'sys.time_zone_info'
  // postgres: add check for in 'pg_timezone_names'
  // sqlite: do not add a check
  timezone text [not null]
}

table Rooms {
  room_id text [pk]
  description text
  label text [not null]
}

table Machines {
  machine_id uuid [pk]
  qr_code_id text [not null]
  nfc_id text [not null]

  controller_type text [not null]
  type MachineType [not null]
  license_plate varchar(7) [not null]
}

enum MachineState {
  pressStart
  running
  idle
  unknown
}

enum MachineType {
  washer
  dryer
}
